# Generated by Django 5.0.6 on 2024-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medixapp', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
