# Generated by Django 5.0.6 on 2024-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medixapp', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
